name: EDM Events Scraper

on:
  schedule:
    - cron: '0 11 * * *'  # Daily at 6:00 AM EST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # Get Chrome version and install matching ChromeDriver
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)

          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
            jq -r --arg version "$MAJOR_VERSION" '
              .channels.Stable.downloads.chromedriver[] 
              | select(.platform == "linux64") 
              | .url')

          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run scraper
        working-directory: backend
        run: python scraper.py

      - name: Commit and push events data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend/data/latest_events.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update EDM events data"
            git pull --rebase origin main  # <- THIS IS THE FIX
            git push origin main
          fi
