name: EDM Events Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Python dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run scraper
        working-directory: backend
        run: |
          python scraper.py

      - name: Pull latest changes with rebase
        run: git pull --rebase origin main

      - name: Commit and push EDM events data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend/data/latest_events.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update EDM events data"
            git push origin main
