name: EDM Events Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6:00 AM UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Debug installed packages
        run: pip list

      - name: Run scraper
        run: |
          cd backend
          python scraper.py
    
    - name: Pull latest changes with rebase
      run: git pull --rebase origin main

    - name: Commit and push EDM events data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add backend/data/latest_events.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update EDM events data"
          git push origin main
        fi